name: Hello World

on:
    schedule:
        - cron: "05,35 * * * *"
    # push

jobs:
    hello-job:
        runs-on: ubuntu-latest
        steps:
            - name: Echo text
              run: echo "Hello, world!"