name: Hello World

on:
    push:
    workflow_dispatch:
    # workflow_dispatch
    # schedule:
    #     - cron: "*/5 * * * *"
    # push

# jobs:
#     hello-job:
#         runs-on: ubuntu-latest
#         steps:
#             - name: Echo text
#               run: echo "Hello, world!"

jobs:
    deploy:
        strategy:
            matrix:
                os: [ubuntu-latest, ubuntu-22.04, windows-latest]
                images: [hello-world, alpine]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Echo Docker Image
              run: docker info

            - name: Run image on ${{ matrix.os }}
              run: docker run ${{ matrix.images }}